name: Reusable K8s Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: Target environment
        required: true
        type: string

      ecr_repository:
        description: ECR repository name
        required: true
        type: string

      docker_image_name:
        description: Application name
        required: true
        type: string

      deployment_name:
        description: Kubernetes deployment name
        required: false
        default: ""
        type: string

      container_name:
        description: Kubernetes container name
        required: false
        default: ""
        type: string

      namespace:
        description: Kubernetes namespace
        required: false
        default: ""
        type: string

      manifest_path:
        description: Manifest directory
        required: false
        default: "k8s"
        type: string

    secrets:
      IAM_ROLE_ARN:
        required: true

      KUBE_CONFIG_DATA:
        required: true

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    env:
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      AWS_REGION: ${{ startsWith(github.ref_name, 'release/') && 'us-east-1'
        || github.ref_name == 'main' && 'us-east-1'
        || github.ref_name == 'staging' && 'us-east-1'
        || 'ap-south-1' }}

      NAMESPACE: ${{ inputs.namespace != '' && inputs.namespace || inputs.environment }}

      DEPLOYMENT_NAME: ${{ inputs.deployment_name != '' && inputs.deployment_name || inputs.docker_image_name }}

      CONTAINER_NAME: ${{ inputs.container_name != '' && inputs.container_name || inputs.docker_image_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube

          echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config

          chmod 600 ~/.kube/config

      - name: Verify Cluster Connectivity
        run: |
          kubectl cluster-info
          kubectl get nodes
